appname = wxapi
httpaddr = "0.0.0.0"
codeaddr = "allbot-license-mysql"
httpport = 8063
runmode = prod
viewspath = "template"
autorender = false
copyrequestbody = true
EnableDocs = true
redislink = allbot-license-redis:6379
redispass = ""
redisdbnum = 2

syncmessage = true
msgpush = true
syncmessagebusinessuri = "http://allbot-license:9090/api/callback/{0}"
logoutbusinessuri = ""

sessionon = true
SessionName = "wxapi"
ServerName = "wxapi"

longlinkenabled = true
longlinkconnecttimeout = "30m"

rabbitmq = false

authserver = "http://v.sxkiss.top"
