appname = wxapi
httpaddr = "0.0.0.0"
codeaddr = "127.0.0.1"
httpport = 8062
runmode = prod
viewspath = "template"
autorender = false
copyrequestbody = true
EnableDocs = true
redislink = 127.0.0.1:6379
redispass = ""
redisdbnum = 2

syncmessage = true
msgpush = true
syncmessagebusinessuri = "http://127.0.0.1:9091/api/callback/{0}"
logoutbusinessuri = ""

sessionon = true
SessionName = "wxapi"
ServerName = "wxapi"

longlinkenabled = true
longlinkconnecttimeout = "30m"

rabbitmq = false

authserver = "http://v.sxkiss.top"
