[adapter]
name = "web"
enabled = true
module = "adapter.web"
class = "WebAdapter"
replyQueue = "xxxbot_reply:web"
replyMaxRetry = 3
replyRetryInterval = 2
logEnabled = true
logLevel = "INFO"

[web]
enable = true
platform = "web"
aliases = ["webchat"]
botWxid = "web-bot-user"
logRawMessage = true

[web.redis]
host = "127.0.0.1"
port = 6379
db = 0
password = ""
queue = "xxxbot"
