[adapter]
name = "web"
<<<<<<< HEAD
enabled = false
=======
enabled = true
>>>>>>> origin/main
module = "adapter.web"
class = "WebAdapter"
replyQueue = "xxxbot_reply:web"
replyMaxRetry = 3
replyRetryInterval = 2
logEnabled = true
logLevel = "INFO"

[web]
<<<<<<< HEAD
enable = false
platform = "web"
aliases = ["webchat"]
botWxid = ""
=======
enable = true
platform = "web"
aliases = ["webchat"]
botWxid = "web-bot-user"
>>>>>>> origin/main
logRawMessage = true

[web.redis]
host = "127.0.0.1"
port = 6379
db = 0
password = ""
queue = "xxxbot"
